# Generated by Django 5.1.4 on 2024-12-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoo',
            options={'ordering': ['srno', 'title', 'date', 'user'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
