# Generated by Django 5.1.4 on 2024-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_Desciption', models.TextField()),
                ('recipe_Image', models.ImageField(upload_to='recipe_images')),
            ],
        ),
    ]
